### ISSUE TITLE
[Bug]: Bug after login

### ISSUE THREAD

**Issue by hazbu** [tomatophp/filament-saas-panel#5]
### What happened?

There is bug after login in 'app' panel
![image](https://github.com/user-attachments/assets/000acb99-01ae-49fd-9283-70a644ae7d07)

And in 'admin' panel, bug if go to teams menu
![image](https://github.com/user-attachments/assets/3dd3c105-08db-4322-a0e3-63956ddc186e)

### How to reproduce the bug

Fresh install filament and following documentation for this plugin

### Package Version

1.0.0

### PHP Version

8.2.12

### Laravel Version

11.36.1

### Which operating systems does with happen with?

Windows

**Comment by hazbu** [comment]
Fixed !, we must change default model to generated model by this plugin inside filament-account.php config

**Comment by Hegabovic** [comment]
can you tell me in steps how to solve it please i get this error 
![Screenshot from 2025-01-08 23-31-28](https://github.com/user-attachments/assets/bfeb98db-7660-4b46-bc08-16553e489444)
